---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-client
spec:
  template:
    metadata:
      labels:
        app: nfs-client
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-volume
          
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-client
spec:
  selector:
    app: nfs-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
