---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
    - protocol: TCP
      port: 2049
  externalIPs:
  # nfs-server node addr, port must be available
  - 192.168.100.202
      
